---
title: Встигнути на автобус
hero_image: images/banner.png
description: Додай код спрайтам, щоб їм вдалося дійти або долетіти до автобуса до того, як він рушить
meta_title: Scratch coding projects for kids and teens | Catch the bus
meta_description: Learn to code in Scratch with the Raspberry Pi Foundation's coding projects for kids and teens. Make a Scratch animation with sprites that run to catch a bus.
version: 4
listed: true
copyedit: false
last_tested: 2021-02-17
steps:
  - 
    title: Ти зробиш
  - 
    title: Створити автобусну сцену
  - 
    title: Кіт Scratch ловить автобус
    completion:
      - engaged
  - 
    title: Бегемот летить до автобуса
  - 
    title: Автобус відправляється
  - 
    title: Запізнення на автобус
  - 
    title: Зміна пункту призначення
    completion:
      - internal
  - 
    title: Швидкий тест
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Вдосконалення твого проєкту
  - 
    title: Що далі?
