title: scratch-tour-bus
hero_image: images/banner.png
description: scratch-tour-bus description
version: 4
listed: false
copyedit: false
last_tested: "2021-02-17"
steps:
  - title: Introduction
  - title: Create your bus scene
  - title: Scratch Cat catches the bus
  - title: Hippo flies to the bus
  - title: The bus leaves
  - title: Missing the bus
  - title: Change Speed
  - title: Reflection
  - title: Upgrade your project
  - title: What next?
