title: Catch the bus
hero_image: images/banner.png
description: Code sprites to walk or fly to a bus before it drives off.
version: 4
listed: false
copyedit: false
last_tested: 2021-02-17
steps:
  - title: Introduction
  - title: Create your bus scene
  - title: Scratch Cat catches the bus
  - title: Hippo flies to the bus
  - title: The bus leaves
  - title: Missing the bus
  - title: Change the destination
  - title: Reflection
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
  - title: Upgrade your project
  - title: What next?
