---
title: बस को पकड़ो
hero_image: images/banner.png
description: बस चलने से पहले चलने या उड़ान भरने के लिए स्प्राइट कोड करें
meta_title: बच्चों और किशोरों के लिए स्क्रैच कोडिंग प्रोजेक्ट | बस को पकड़ो
meta_description: बच्चों और किशोरों के लिए रास्पबेरी पाई फाउंडेशन की कोडिंग प्रोजेक्ट से शुरुआत से कोड करना सीखें। बस चलने से पहले चलने या उड़ान भरने के लिए स्प्राइट कोड करें
version: 4
listed: true
copyedit: false
last_tested: 2021-02-17
steps:
  - 
    title: आप बनाएंगे
  - 
    title: अपना बस दृश्य बनाएं
  - 
    title: Scratch Cat बस पकड़ती है
    completion:
      - engaged
  - 
    title: हिप्पो बस के लिए उड़ान भरता है
  - 
    title: बस निकलती है
  - 
    title: बस छुटना
  - 
    title: डेस्टिनेशन बदलें
    completion:
      - internal
  - 
    title: प्रश्नोत्तरी
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: अपना प्रोजेक्ट अपग्रेड करें
  - 
    title: आगे क्या?
