---
title: バスに乗る
hero_image: images/banner.png
description: バスの出発前にスプライトを到着させるコードをつくります
meta_title: 子供と十代の若者向けのScratch コーディング プロジェクト |バスに乗る
meta_description: Raspberry Pi Foundationの子どもと十台の若者向けのコーディングプロジェクトでScratchによるコーディングを学びましょう。バスに間に合うように走るスプライトを使って、Scratchアニメーションを作ります。
pdf: resources/catch-the-bus.pdf
version: 4
listed: true
copyedit: false
last_tested: 2021-02-17
steps:
- title: 作るもの
- title: バスの場面を作る
- title: スクラッチキャットがバスに乗る
  completion:
  - engaged
- title: カバはバスに向かって飛ぶ
- title: バスの出発
- title: バスに乗り遅れる
- title: 目的地を変更する
  completion:
  - internal
- title: ふりかえり
  knowledge_quiz:
    path: quiz1
    version: 1
    questions: 3
    passing_score: 3
  completion:
  - external
- title: プロジェクトをアップグレードする