---
title: Dal y bws
hero_image: images/banner.png
description: Cyfle i ysgrifennu cod i ddweud wrth y corlun i gerdded neu hedfan i'r bws cyn iddo adael
meta_title: Scratch coding projects for kids and teens | Catch the bus
meta_description: Learn to code in Scratch with the Raspberry Pi Foundation's coding projects for kids and teens. Make a Scratch animation with sprites that run to catch a bus.
version: 4
listed: true
copyedit: false
last_tested: 2021-02-17
steps:
  - 
    title: You will make
  - 
    title: Creu dy olygfa bws
  - 
    title: Scratch Cat yn dal y bws
    completion:
      - engaged
  - 
    title: Mae'r hipo yn hedfan i'r bws
  - 
    title: Mae'r bws yn gadael
  - 
    title: Colli'r bws
  - 
    title: Newid y gyrchfan
    completion:
      - internal
  - 
    title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Uwchraddio dy brosiect
  - 
    title: Beth nesaf?
