---
title: Pegue o ônibus
hero_image: images/banner.png
description: Atores de código para caminhar ou voar até o ônibus antes que ele desapareça
meta_title: Scratch coding projects for kids and teens | Catch the bus
meta_description: Learn to code in Scratch with the Raspberry Pi Foundation's coding projects for kids and teens. Make a Scratch animation with sprites that run to catch a bus.
version: 4
listed: true
copyedit: false
last_tested: 2021-02-17
steps:
  - 
    title: You will make
  - 
    title: Crie o cenário do teu ônibus
  - 
    title: O Gato Scratch alcança o ônibus
    completion:
      - engaged
  - 
    title: O hipopótamo alcança o ônibus voando
  - 
    title: O ônibus parte
  - 
    title: Perdendo o ônibus
  - 
    title: Mudando o destino
    completion:
      - internal
  - 
    title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Melhore o seu projeto
  - 
    title: E agora?
