---
title: Pegue o ônibus
hero_image: images/banner.png
description: Atores de código para caminhar ou voar até o ônibus antes que ele desapareça
meta_title: Projetos de codificação Scratch para crianças e adolescentes | Pegar o ônibus
meta_description: Aprenda a programar no Scratch com os projetos de codificação da Raspberry Pi Foundation para crianças e adolescentes. Faça uma animação do Scratch com atores que correm para pegar um ônibus.
version: 4
listed: true
copyedit: false
last_tested: 2021-02-17
steps:
  - 
    title: Introdução
  - 
    title: Crie o cenário do teu ônibus
  - 
    title: O Gato Scratch alcança o ônibus
    completion:
      - engaged
  - 
    title: O hipopótamo alcança o ônibus voando
  - 
    title: O ônibus parte
  - 
    title: Perdendo o ônibus
  - 
    title: Mudando o destino
    completion:
      - internal
  - 
    title: Quiz rápido
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Melhore o seu projeto
  - 
    title: E agora?
