---
title: Agafa l'autobús
hero_image: images/banner.png
description: Programa els personatges per caminar o volar fins a l'autobús abans que marxi
meta_title: Projectes de programació Scratch per a nens i adolescents | Introducció a Scratch
meta_description: Apreneu a programar a Scratch amb els projectes de programació de la Fundació Raspberry Pi per a nens i adolescents. Crea amb Scratch animacions, jocs, aplicacions i molt més.
version: 4
listed: true
copyedit: false
last_tested: 2021-02-17
steps:
  - title: Tu faràs
  - title: Crea la teva escena d'autobús
  - title: El gat de Scratch agafa l'autobús
    completion:
      - engaged
  - title: L'hipopòtam corre cap a l'autobús
  - title: L'autobús marxa
  - title: Falta l'autobús
  - title: Canvia el destí
    completion:
      - internal
  - title: Test ràpid
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - title: Actualitza el teu projecte
  - title: I ara què ve?
