---
title: Stihni autobus
hero_image: images/banner.png
description: Nakóduj skřítky tak, aby došli nebo doletěli k autobusu, než se rozjede
meta_title: Kódovací projekty ve Scratchi pro děti a náctileté | Stihni autobus
meta_description: Nauč se kódovat ve Scratchi pomocí kódovacích projektů pro děti a náctileté od nadace Raspberry Pi Foundation. Vytvoř si animaci ve Scratchi se skřítky, kteří se snaží doběhnout autobus.
version: 4
listed: true
copyedit: false
last_tested: 2021-02-17
steps:
  - 
    title: Co budeš dělat
  - 
    title: Vytvoř svou autobusovou scénu
  - 
    title: Kocour Scratch stihne autobus
    completion:
      - engaged
  - 
    title: Hroch letí na autobus
  - 
    title: Autobus odjíždí
  - 
    title: Nestíhá autobus
  - 
    title: Změň cíl
    completion:
      - internal
  - 
    title: Rychlý kvíz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Vylepši svůj projekt
  - 
    title: Co dál?
