---
title: ಬಸ್ ಹಿಡಿಯಿರಿ
hero_image: images/banner.png
description: Code sprites to walk or fly to the bus before it drives off
meta_title: Scratch coding projects for kids and teens | Catch the bus
meta_description: Learn to code in Scratch with the Raspberry Pi Foundation's coding projects for kids and teens. Make a Scratch animation with sprites that run to catch a bus.
version: 4
listed: true
copyedit: false
last_tested: 2021-02-17
steps:
  - 
    title: You will make
  - 
    title: ನಿಮ್ಮ ಬಸ್ ದೃಶ್ಯವನ್ನು ರಚಿಸಿ
  - 
    title: ಸ್ಕ್ರಾಚ್ ಕ್ಯಾಟ್ ಬಸ್ ಹಿಡಿಯುತ್ತದೆ
    completion:
      - engaged
  - 
    title: ಹಿಪ್ಪೋ ಬಸ್ಸಿಗೆ ಹಾರುತ್ತದೆ
  - 
    title: ಬಸ್ ಹೊರಡುತ್ತದೆ
  - 
    title: ಬಸ್ ತಪ್ಪುವುದು
  - 
    title: ತಲುಪುವ ಸ್ಥಳವನ್ನು ಬದಲಾಯಿಸಿ
    completion:
      - internal
  - 
    title: Quick quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: ನಿಮ್ಮ ಯೋಜನೆಯನ್ನು ಅಪ್‌ಗ್ರೇಡ್ ಮಾಡಿ
  - 
    title: ಮುಂದೆ ಏನು?
