---
title: Toma el autobús
hero_image: images/banner.png
description: Codifica objetos para caminar o volar hasta el autobús antes de que se ponga en marcha
meta_title: Scratch coding projects for kids and teens | Catch the bus
meta_description: Learn to code in Scratch with the Raspberry Pi Foundation's coding projects for kids and teens. Make a Scratch animation with sprites that run to catch a bus.
version: 4
listed: true
copyedit: false
last_tested: 2021-02-17
steps:
  - 
    title: Lo que harás
  - 
    title: Crea tu escena de autobús
  - 
    title: El gato de Scratch toma el autobús
    completion:
      - engaged
  - 
    title: El hipopótamo vuela hacia el autobús
  - 
    title: El autobús se va
  - 
    title: Perder el autobús
  - 
    title: Cambia el destino
    completion:
      - internal
  - 
    title: Examen rápido
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Mejora tu proyecto
  - 
    title: '¿Qué sigue?'
