---
title: Złap autobus
hero_image: images/banner.png
description: Zaprogramuj duszka, aby doszedł lub przeleciał do autobusu, zanim ten odjedzie
meta_title: Scratch coding projects for kids and teens | Catch the bus
meta_description: Learn to code in Scratch with the Raspberry Pi Foundation's coding projects for kids and teens. Make a Scratch animation with sprites that run to catch a bus.
version: 4
listed: true
copyedit: false
last_tested: 2021-02-17
steps:
  - 
    title: Co będziesz robić
  - 
    title: Stwórz swoją scenę z autobusem
  - 
    title: Kot Scratch łapie autobus
    completion:
      - engaged
  - 
    title: Hipcio leci do autobusu
  - 
    title: Autobus odjeżdża
  - 
    title: Spóźnienie się na autobus
  - 
    title: Zmień miejsce docelowe
    completion:
      - internal
  - 
    title: Szybki quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - 
    title: Ulepsz swój projekt
  - 
    title: Co dalej?
