---
title: Hinn med bussen
hero_image: images/banner.png
description: Koda sprajter att gå eller flyga till bussen innan den kör iväg
version: 4
listed: true
copyedit: false
last_tested: 2021-02-17
steps:
  - title: Du kommer skapa
  - title: Skapa din bussscen
  - title: Scratchkatten hinner med bussen
    completion:
      - engaged
  - title: Flodhästen flyger till bussen
  - title: Bussen går
  - title: Missar bussen
  - title: Ändra destinationen
    completion:
      - internal
  - title: Snabbt quiz
    knowledge_quiz:
      path: quiz1
      version: 1
      questions: 3
      passing_score: 3
    completion:
      - external
  - title: Uppgradera ditt projekt
  - title: Vad händer nu?
